# Generated by Django 5.1 on 2024-08-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0022_rename_adoption_time_adoption_adopted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='balance_after_adoption',
            field=models.IntegerField(null=True),
        ),
    ]
