# Generated by Django 5.1 on 2024-08-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0023_alter_adoption_balance_after_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='balance_after_adoption',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
