# Generated by Django 5.1 on 2024-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
